org: lfedge
image: eve-vmagent
config:
  binds:
    - /:/hostfs
    - /proc:/hostfs/proc
    - /sys:/hostfs/sys
    - /dev:/dev
    - /run:/run
    - /etc/resolv.conf:/etc/resolv.conf
    - /persist:/persist
    - /config:/config:ro